# Generated by Django 4.2.26 on 2026-02-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_table_rename_delivered_at_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
