# Generated by Django 4.2.26 on 2026-02-22 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery', '0006_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Driver assigned to deliver this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Is driver currently available for deliveries'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle registration number', max_length=30),
        ),
    ]
