# Generated by Django 4.2.27 on 2026-02-23 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery', '0008_alter_order_status_driverlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20)),
                ('house_flat', models.CharField(help_text='House/Flat/Floor/Building', max_length=200)),
                ('area_street', models.CharField(help_text='Area, Street, Sector, Village', max_length=300)),
                ('landmark', models.CharField(blank=True, help_text='Nearby landmark', max_length=200)),
                ('city', models.CharField(default='Hyderabad', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('full_address', models.TextField(blank=True, help_text='Full formatted address string')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
